### ISSUE TITLE
Double dqn代码

### ISSUE THREAD

**Issue by Zekun-Cai** [datawhalechina/leedeeprl-notes#13]
https://github.com/datawhalechina/leedeeprl-notes/blob/0a9c1bd78d3d5d30f6c11c9d43e0e73863cadbf4/codes/double_dqn/dqn.py#L98-L108
这里使用的策略是Nature dqn而不是Double dqn吧？

**Comment by JohnJim0816** [comment]
感谢提醒！已更新～

**Comment by Zekun-Cai** [comment]
https://github.com/datawhalechina/leedeeprl-notes/blob/8b2e54ef859870ab6c1ede9f4c3d8a88de4a152c/codes/DoubleDQN/agent.py#L104
`next_q_values = self.policy_net(next_state_batch) `

**Comment by JohnJim0816** [comment]
是的，已改～
