### ISSUE TITLE
请问怎么打不开笔记了？

### ISSUE THREAD

**Issue by xiaojz227** [datawhalechina/leedeeprl-notes#14]

**Comment by qiwang067** [comment]
笔记是可以正常访问的，如果打不开的话，可以试试如下的方法：
- 切换浏览器
- 修改 hosts，具体可以参考：https://zhuanlan.zhihu.com/p/107334179
- 科学上网（这个最有效）

**Comment by xiaojz227** [comment]
科学上网果然很快打开~谢谢啦

**Comment by qiwang067** [comment]
> 科学上网果然很快打开~谢谢啦

客气了
