### ISSUE TITLE
关于codes中Q-learning部分的疑问

### ISSUE THREAD

**Issue by haoqiangyang1998** [datawhalechina/leedeeprl-notes#15]
在运行命令，python main.py --train 0时出现如下报错：
![image](https://user-images.githubusercontent.com/57616364/103543190-114c1280-4ed9-11eb-94d8-8fbd086acbed.png)

是因为eval函数不接受参数saved_model_path吗？

**Comment by JohnJim0816** [comment]
您好，已更新～

**Comment by haoqiangyang1998** [comment]
多谢~
