### ISSUE TITLE
https://datawhalechina.github.io/leedeeprl-notes/#/chapter2/chapter2内容发现一处错别字

### ISSUE THREAD

**Issue by YushuaiRen** [datawhalechina/leedeeprl-notes#17]
https://github.com/datawhalechina/leedeeprl-notes/blob/master/docs/chapter2/chapter2.md
公式（14）上面一段话中存在错字

使得每一次『得带』不需要更新所有的状态  ---->>  使得每一次『迭代』不需要更新所有的状态

**Comment by qiwang067** [comment]
感谢您的纠错，错误已更正，笔记已更新
