### ISSUE TITLE
Policy Gradient 的疑问

### ISSUE THREAD

**Issue by Ynjxsjmh** [datawhalechina/leedeeprl-notes#19]
[第四章 策略梯度](https://datawhalechina.github.io/leedeeprl-notes/#/chapter4/chapter4) 有如下表述：

![image](https://user-images.githubusercontent.com/40143136/107244593-27656980-6a69-11eb-91a1-c793404dfbfc.png)

> 假设你在 st​ 执行 at​，最后发现 τ 的奖励是正的， 那你就要增加这一项的概率。
> 反之，在 st​ 执行 at​ 会导致 τ 的奖励变成负的， 你就要减少这一项的概率。

我能明白这两句话是在表述我们的目的，但是公式中哪一部分在实现这个目的呢？

![image](https://user-images.githubusercontent.com/40143136/107244962-9773ef80-6a69-11eb-8198-58bdd7ed565a.png)

**Comment by qiwang067** [comment]
这边其实没有那么直观，建议你看下周博磊老师的「强化学习纲要 第五课 策略优化基础 下」：
https://www.bilibili.com/video/BV1ia4y1x7Va

**Comment by Ynjxsjmh** [comment]
多谢，视频从 4:02 开始是与此部分相关的。我看了后感觉是在和 Maximum likelihood 进行对比时，将奖励函数的正负作为对 likelihood 的加权后，得出的这个结论。

但是对于乘上奖励函数后，`θ <- θ + η · ∇R_{θ}` 调整参数大小这一步就可以实现让好的动作输出概率增大，差的动作输出概率减小么？θ 越大 s_{t}​ 执行 a_{t} 的概率越大么？

**Comment by qiwang067** [comment]
你这边的理解有个问题，如下图所示的式子是在做梯度上升，θ不一定越大，这边实际上是一个优化的过程，优化的结果是  s_{t}​ 执行 a_{t} 的概率越大

![image](https://user-images.githubusercontent.com/22296010/107456629-76a3bb00-6b8b-11eb-8f70-f6575efd6923.png)
