### ISSUE TITLE
chapter2 bootstrap的翻译

### ISSUE THREAD

**Issue by Data-Designer** [datawhalechina/leedeeprl-notes#22]
这里应该是叫自助采样，而非拔靴自助[docs/chapter2/chapter2.md](url)

**Comment by qiwang067** [comment]
感谢您的反馈，第二章的 bootstrapping 并非是自助采样，其具体含义可参照下图
![image](https://user-images.githubusercontent.com/22296010/110225541-66c88e00-7f21-11eb-8d24-e6e4489a79a5.png)
