### ISSUE TITLE
请问是不是还不支持完整汇聚全部章节成PDF？

### ISSUE THREAD

**Issue by KennyNg-19** [datawhalechina/leedeeprl-notes#23]

**Comment by qiwang067** [comment]
感谢您的提问，因为笔记还在不断更新中，所以暂不考虑发布 pdf；
如果您想在本地更方便地看笔记的话，建议你下载本仓库的全部文件，然后使用 typora 打开 markdown 文件。

**Comment by qiwang067** [comment]
您好，pdf 版本已经发布，下载地址：https://github.com/datawhalechina/easy-rl/releases/tag/v1.0.0
