### ISSUE TITLE
PPO中出现一点笔误.

### ISSUE THREAD

**Issue by FYYFU** [datawhalechina/leedeeprl-notes#8]
![图片](https://user-images.githubusercontent.com/37999885/101854432-80656e00-3b9c-11eb-9f12-6298c548c80c.png)
 这里第一行的PPO, 是否应该改为TRPO?

**Comment by yyysjz1997** [comment]
感谢你的反馈，不过图片加载不出来，不知道是不是我这里的问题。方便使用github的code引用标注一下呢？

**Comment by FYYFU** [comment]
> 感谢你的反馈，不过图片加载不出来，不知道是不是我这里的问题。方便使用github的code引用标注一下呢？

不好意思,好像是在 https://github.com/datawhalechina/leedeeprl-notes/blob/master/docs/chapter5/chapter5.md. 这个文件中的.
```
PPO 是很难处理的，因为它是把 KL 散度约束当做一个额外的约束，没有放目标(objective)里面，所以它很难算。所以不想搬石头砸自己的脚的话， 你就用 PPO 不要用 TRPO。看文献上的结果是，PPO 跟 TRPO 可能性能差不多，但 PPO 在实现上比 TRPO 容易的多。
```

**Comment by qiwang067** [comment]
感谢您的纠错，的确要改成 TRPO，教程已更新，错误已纠正。

> ![图片](https://user-images.githubusercontent.com/37999885/101854432-80656e00-3b9c-11eb-9f12-6298c548c80c.png)
> 这里第一行的PPO, 是否应该改为TRPO?
